export const socialLinks = {
    facebook:
      "https://www.facebook.com/people/Pfpdao-Dao/pfbid0HnyBv1rP4H2DBar9LwrYRxooXNrXnLaNH2AeyfVfEcrRWyy73fHaq4qt62YDN4p5l",
    telegram: "https://t.me/pfp_dao",
    twitter: "https://twitter.com/PFP_DAO_io",
    instagram: "https://www.instagram.com/PFPDAO/",
    linkedin: "https://www.linkedin.com/company/pfp-dao/",
    tiktok: "http://www.tiktok.com/@pfp_dao_io",
    youtube: "https://www.youtube.com/@PFP-DAO",
    medium: "https://medium.com/@pfp-dao",
    lens: "https://lenster.xyz/u/drips",
    pinterest: "https://pin.it/7GWrRE6",
    linktree: "https://linktr.ee/pfp_dao",
    discord: "https://discord.gg/HswTwKc63C",
    telegramCN: "https://t.me/pfp_dao_cn",
    bilibili: "https://space.bilibili.com/4935892",
    douyin: "https://v.douyin.com/UjY4ABC/",
    xiaohongshu:
      "https://www.xiaohongshu.com/user/profile/5ee4e3580000000001005e84/",
    weibo: "https://weibo.com/u/7839767152",
    wechat: "https://work.weixin.qq.com/kfid/kfce741809d233f4f2f",
    gitbook: "https://mirror-planet.gitbook.io/pfp-dao.io",
    rssApi: "https://paragraph.xyz/api/blogs/@pfp_dao_io/subscribe",
    rssBlog: "https://paragraph.xyz/@pfp_dao_io",
    collab: "https://forms.gle/i4avjgpfJX19UtPCA",
  };